# Generated by Django 3.2.8 on 2021-12-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danie',
            fields=[
                ('idDanie', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=45)),
                ('Rodzaj', models.CharField(max_length=45)),
                ('Cena', models.FloatField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Restauracja',
            fields=[
                ('idRestauracja', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=45)),
                ('Adres', models.CharField(max_length=45)),
                ('Rodzaj_dan', models.CharField(max_length=45)),
                ('Cena_dostawy', models.FloatField(max_length=12)),
                ('Kategoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('idZamowienie', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Adres', models.CharField(max_length=45)),
                ('Telefon', models.IntegerField()),
                ('Email', models.CharField(max_length=45)),
                ('Data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Szczegoly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ilosc', models.IntegerField()),
                ('Cena', models.FloatField(max_length=45)),
                ('Danie_idDanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenie.danie')),
                ('Zamowienie_idZamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenie.zamowienie')),
            ],
        ),
        migrations.AddField(
            model_name='danie',
            name='idRestauracja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenie.restauracja'),
        ),
    ]
