# Generated by Django 3.2.8 on 2021-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0002_auto_20211211_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danie',
            name='idDanie',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='restauracja',
            name='idRestauracja',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='idZamowienie',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
